List<String> communityCatagories = [
  "Q&As",
  "Funny",
  "Cringe & Facepalm",
  "Reddit Meta",
  "Memes",
  "Interesting",
  "Ethics & Philosophy",
  "Career",
  "Role-Playing Games",
  "Stories & Confessions",
  "News",
  "Action Games",
  "Anime & Manga",
  "Places in Europe",
  "Animals & Pets",
  "Places in North America",
  "Podcasts",
  "Cars & Trucks",
  "Tabletop Games",
  "Gaming News & Discussion",
  "Law",
  "Food industry & Restaurants",
  "Movie News & Discussion",
  "Personal Finance",
  "Adventure Games",
  "Computers & Hardware",
  "Celebrities",
  "Paranormal & Unexplained",
  "Beauty & Grooming",
  "Amazing"
];
